/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package censo;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import dba.Mysql;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author kecha
 */
public class DatosEstadisticos extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection conn;
    Statement sent;
    /**
     * Creates new form DatosEstadisticos
     */
    public DatosEstadisticos(){
        initComponents();
        setLocationRelativeTo(null);
        conn = (Connection) Mysql.getConnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1229, 768));
        setMinimumSize(new java.awt.Dimension(1229, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 430, 170));

        jLabel3.setBackground(new java.awt.Color(153, 0, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UBICACION GEOGRAFICA (A)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 480, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 430, 170));

        jLabel4.setBackground(new java.awt.Color(102, 0, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRINCIPALES CARACTERISTICAS DE LA VIVIENDA (B)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 490, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 430, 170));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MORTALIDAD (D)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 430, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMIGACION INTERNACIONAL (C)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 430, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 430, 170));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("MOSTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 110, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 430, 170));

        jPanel6.setPreferredSize(new java.awt.Dimension(430, 170));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura1-removebg-preview (1).png"))); // NOI18N
        jButton2.setText("ATRAS");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PERSONAS CON ALGUNA DIFICULTADAD PERMANENTE (E)");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 496, 430, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PRINCIPALES CARACTERISTICAS DE LA PERSONA (F)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 496, 430, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        jTextField8.setText("jTextField8");
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        jTextField9.setText("jTextField9");
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        jTextField10.setText("jTextField10");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jTextField11.setText("jTextField11");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jTextField12.setText("jTextField12");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jTextField13.setText("jTextField13");
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jTextField14.setText("jTextField14");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jTextField15.setText("jTextField15");
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jTextField16.setText("jTextField16");
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        jTextField17.setText("jTextField17");
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jTextField18.setText("jTextField18");
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jTextField19.setText("jTextField19");
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jTextField20.setText("jTextField20");
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jTextField21.setText("jTextField21");
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jTextField22.setText("jTextField22");
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conn = (Connection) Mysql.getConnection();
            String sql = "SELECT COUNT(CodMunicipal)AS TotalPersonas from ubicaciongeografica" ;
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            
            jTextField1.setText (rs.getString("TotalPersonas"));
            
            datosDepartamento();
            techoVivienda();
            deViaje();
            muerte();
            dificultad();
            sexo();
            
            
        }catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    
    
    public void sexo(){
        
        try {
            
            String sql = "SELECT COUNT(idca)AS Sexo from caracteristicaspersona where Sexo ='Hombre'";
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();   
            jTextField21.setText (rs.getString("Sexo"));
            
            sql = "SELECT COUNT(idca)AS Sexo from caracteristicaspersona where Sexo ='Mujer'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField22.setText (rs.getString("Sexo"));
           
            }
        catch (Exception e) {
            e.printStackTrace();
        }
     
     
        JFreeChart barra = null;
        DefaultCategoryDataset datos;
        datos = new DefaultCategoryDataset();
        
        datos.setValue(Integer.parseInt(jTextField21.getText()), "Grafico F", "Hombre");
        datos.setValue(Integer.parseInt(jTextField22.getText()), "Grafico F", "Mujer");
        
        barra = ChartFactory.createBarChart3D(
                "CARACTERISTICAS DE LA PERSONA", 
                "PORCENTAJES DEL CAPITULO F",
                "Porcentajes",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(barra);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(jLabel11.getSize());
        
        jPanel6.setLayout (new BorderLayout());
        jPanel6.add (panel, BorderLayout.NORTH);
        
        pack();
        repaint();
        
        
    }
    
    
    
    public void dificultad(){
        
        try {
            
            String sql = "SELECT COUNT(idd)AS dificult from dificultadpermanente where dificult ='SI'";
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();   
            jTextField19.setText (rs.getString("dificult"));
            
            sql = "SELECT COUNT(idd)AS dificult from dificultadpermanente where dificult ='NO'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField20.setText (rs.getString("dificult"));
           
            }
        catch (Exception e) {
            e.printStackTrace();
        }
     
     
        JFreeChart barra = null;
        DefaultCategoryDataset datos;
        datos = new DefaultCategoryDataset();
        
        datos.setValue(Integer.parseInt(jTextField19.getText()), "Grafico E", "Con alguna dificultad");
        datos.setValue(Integer.parseInt(jTextField20.getText()), "Grafico E", "Sin ninguna dificultad");
        
        barra = ChartFactory.createBarChart3D(
                "PERSONAS CON DIFICULTAD PERMANENTE", 
                "PORCENTAJES DEL CAPITULO E",
                "Porcentajes",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(barra);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(jLabel10.getSize());
        
        jPanel5.setLayout (new BorderLayout());
        jPanel5.add (panel, BorderLayout.NORTH);
        
        pack();
        repaint();
        
    }
    
    
    public void muerte(){
        
        try {
            
            String sql = "SELECT COUNT(idm)AS Muerte from mortalidad where Muerte ='SI'";
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();   
            jTextField17.setText (rs.getString("Muerte"));
            
            sql = "SELECT COUNT(idm)AS Muerte from mortalidad where Muerte ='NO'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField18.setText (rs.getString("Muerte"));
           
            }
        catch (Exception e) {
            e.printStackTrace();
        }
     
     
        JFreeChart barra = null;
        DefaultCategoryDataset datos;
        datos = new DefaultCategoryDataset();
        
        datos.setValue(Integer.parseInt(jTextField17.getText()), "Grafico D", "Murio");
        datos.setValue(Integer.parseInt(jTextField18.getText()), "Grafico D", "No Murio");
        
        barra = ChartFactory.createBarChart3D(
                "MORTALIDAD", 
                "PORCENTAJES DEL CAPITULO D",
                "Porcentajes",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(barra);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(jLabel8.getSize());
        
        jPanel3.setLayout (new BorderLayout());
        jPanel3.add (panel, BorderLayout.NORTH);
        
        pack();
        repaint();
        
        
    }
    
    
    public void deViaje(){
        
        try {
            
            String sql = "SELECT COUNT(ide)AS deViaje from emigracioninterlacional where deViaje ='SI'";
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();   
            jTextField15.setText (rs.getString("deViaje"));
            
            sql = "SELECT COUNT(ide)AS deViaje from emigracioninterlacional where deViaje ='NO'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField16.setText (rs.getString("deViaje"));
           
            }
        catch (Exception e) {
            e.printStackTrace();
        }
     
     
        JFreeChart barra = null;
        DefaultCategoryDataset datos;
        datos = new DefaultCategoryDataset();
        
        datos.setValue(Integer.parseInt(jTextField15.getText()), "Grafico C", "De Viaje");
        datos.setValue(Integer.parseInt(jTextField16.getText()), "Grafico C", "No viajo");
        
        barra = ChartFactory.createBarChart3D(
                "EMIGRACION INTERNACIONAL", 
                "PORCENTAJES DEL CAPITULO C",
                "Porcentajes",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(barra);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(jLabel9.getSize());
        
        jPanel4.setLayout (new BorderLayout());
        jPanel4.add (panel, BorderLayout.NORTH);
        
        pack();
        repaint();
        
    }
    
    
    public void techoVivienda(){
        try {
            
            String sql = "SELECT COUNT(idv)AS TechoVivienda from vivienda where TechoVivienda ='Otro'";
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();   
            jTextField10.setText (rs.getString("TechoVivienda"));
            
            sql = "SELECT COUNT(idv)AS TechoVivienda from vivienda where TechoVivienda ='Teja de arcilla, Teja de Cemento, Fibrocementro'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField11.setText (rs.getString("TechoVivienda"));
            
            sql = "SELECT COUNT(idv)AS TechoVivienda from vivienda where TechoVivienda ='Losa de hormigon armado'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField12.setText (rs.getString("TechoVivienda"));
            
            sql = "SELECT COUNT(idv)AS TechoVivienda from vivienda where TechoVivienda ='Calamina o plancha metaica'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField13.setText (rs.getString("TechoVivienda"));
            
            sql = "SELECT COUNT(idv)AS TechoVivienda from vivienda where TechoVivienda ='Paja, Palma, Caña, Barro'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField14.setText (rs.getString("TechoVivienda"));
           
            }
        catch (Exception e) {
            e.printStackTrace();
        }
     
     
        JFreeChart barra = null;
        DefaultCategoryDataset datos;
        datos = new DefaultCategoryDataset();
        
        datos.setValue(Integer.parseInt(jTextField10.getText()), "Grafico B", "Otro");
        datos.setValue(Integer.parseInt(jTextField11.getText()), "Grafico B", "Teja de arcilla, Teja de Cemento, Fibrocementro");
        datos.setValue(Integer.parseInt(jTextField12.getText()), "Grafico B", "Losa de hormigon armado");
        datos.setValue(Integer.parseInt(jTextField13.getText()), "Grafico B", "Calamina o plancha metaica");
        datos.setValue(Integer.parseInt(jTextField14.getText()), "Grafico B", "Paja, Palma, Caña, Barro");
        
        
        barra = ChartFactory.createBarChart3D(
                "PRINCIPALES CARACTERISTICAS DE LA VIVIENDA", 
                "PORCENTAJES DEL CAPITULO B",
                "Porcentajes",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(barra);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(jLabel5.getSize());
        
        jPanel2.setLayout (new BorderLayout());
        jPanel2.add (panel, BorderLayout.NORTH);
        
        pack();
        repaint();
    }
    
    
    
    public void datosDepartamento(){
     try {
            conn =(Connection) Mysql.getConnection();
            String sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Cochabamba'";
            sent = (Statement) conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();   
            jTextField1.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='La Paz'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField2.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Pando'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField3.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Beni'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField4.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Santa Cruz'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField5.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Oruro'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField6.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Potosi'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField7.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='Chuquisaca'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField8.setText (rs.getString("Ciudad"));
            
            sql = "SELECT COUNT(CodMunicipal)AS Ciudad from ubicaciongeografica where Ciudad ='tarija'";
            sent = (Statement) conn.createStatement();
            rs = sent.executeQuery(sql);
            rs.next();   
            jTextField9.setText (rs.getString("Ciudad"));
           
            }
        catch (Exception e) {
            e.printStackTrace();
        }
     
     
        JFreeChart barra = null;
        DefaultCategoryDataset datos;
        datos = new DefaultCategoryDataset();
        
        datos.setValue(Integer.parseInt(jTextField1.getText()), "Grafico A", "Cochabamba");
        datos.setValue(Integer.parseInt(jTextField2.getText()), "Grafico A", "La Paz");
        datos.setValue(Integer.parseInt(jTextField3.getText()), "Grafico A", "Pando");
        datos.setValue(Integer.parseInt(jTextField4.getText()), "Grafico A", "Beni");
        datos.setValue(Integer.parseInt(jTextField5.getText()), "Grafico A", "Santa Cruz");
        datos.setValue(Integer.parseInt(jTextField6.getText()), "Grafico A", "oruro");
        datos.setValue(Integer.parseInt(jTextField7.getText()), "Grafico A", "Potosi");
        datos.setValue(Integer.parseInt(jTextField8.getText()), "Grafico A", "Chuquisaca");
        datos.setValue(Integer.parseInt(jTextField9.getText()), "Grafico A", "Tarija");
        
        
        barra = ChartFactory.createBarChart3D(
                "UBICACION GEOGRAFICA", 
                "PORCENTAJES DEL CAPITULO A",
                "Porcentajes",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(barra);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(jLabel2.getSize());
        
        jPanel1.setLayout (new BorderLayout());
        jPanel1.add (panel, BorderLayout.NORTH);
        
        pack();
        repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        FuncionesAdministrador ad = new  FuncionesAdministrador();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEstadisticos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
